### ISSUE TITLE
large amount of transactions

### ISSUE THREAD

**Issue by stellanhaglund** [kibae/pg-logical-replication#17]
When I update to big tables with say 500k rows and about 30 column i never get any result in the client.
Any idea why?

**Comment by kibae** [comment]
Hello, @stellanhaglund 
I haven't tested huge transactions. Let me ask you a few questions to solve.

1. What version are you using? Are you using the recently released 2.x version?
2. If you are using 2.x, which [output plugin](https://github.com/kibae/pg-logical-replication#4-output-plugins) do you use?
3. Does the result of a small transaction before a huge transaction arrive well?
4. Are the results of a small transaction right after a huge transaction arrive?

**Comment by stellanhaglund** [comment]
I will check the version in a moment.
Im using wal2json but i needed to modify the JSON.parse(buffer.toString())
part to use json-stream instead because i got errors with big jsons that
the string was too big.

But small transactions before big work, But im pretty sure small after big
doesn’t will try again.

I was thinking that the big transaction takes too long to download or
something, but I’m not sure if it could be a postgres setting thing maybe?

fre 30 sep. 2022 kl. 04:25 skrev Kibae Shin ***@***.***>:

**Comment by stellanhaglund** [comment]
yeah it's the 2.x version, and I did an ugly workaround to solve a problem where it wasn't able to create a big enough string here

``` 
  parse(buffer: Buffer, cb: Function): any {
    let stream = Readable.from(buffer);

    const pipeline = chain([
      stream,
      Pick.withParser({filter: 'change'}),
      streamArray()
    ])    

    pipeline.on('data', (data) => {
      cb(data)
    })
  }
  
  ```

**Comment by kibae** [comment]
@stellanhaglund 
I reproduced the same problem when using the wal2json plugin.
I think in order to solve this issue in all output plugins, it should be changed to handle each row event rather than trx chunk. Just like the code you suggested. Could you possibly push/PR your code to the "**next-each-event**" branch? I created that branch.
It's a big change, so let's fix this issue in 3.x version. 🙏

How about using the pgoutput plugin for now? This problem did not occur with the pgoutput plugin.

- https://github.com/kibae/pg-logical-replication/blob/main/src/test/decoder-pgoutput.spec.ts#L228
- https://github.com/kibae/pg-logical-replication/blob/next-each-event/infra/docker-pg-logical-replication/image/docker-entrypoint-initdb.d/11-fill-data.sh#L12

**Comment by stellanhaglund** [comment]
To make sure I understand what you mean.

There is a difference in how wal2json and pgoutput works?
To me it looks like there’s no other way than to get the complete transaction and parse it from wal2json?
Does pgoutput do it another way?

and for using pgoutput I chose wal2json because it’s a simple format to parse to json objects, what does the pgoutput format look like?

**Comment by stellanhaglund** [comment]
And sure I can commit my code if it is any help

**Comment by kibae** [comment]
pgoutput is in low level and raw format.
https://www.postgresql.org/docs/current/protocol-logical-replication.html

If 500k changes occur in DB, 500k change events are delivered instead of 1 transaction chunk. So this issue was not an issue for this plugin.
